ONLYOFFICE/core

DesktopEditor/raster/Metafile/Common/MetaFileRenderer.h
DesktopEditor/raster/Metafile/Wmf/WmfFile.h
DesktopEditor/raster/Metafile/Wmf/WmfPlayer.cpp
DesktopEditor/raster/Metafile/Wmf/WmfPlayer.h

Fix the problem with rendering WMF files

Fix bug #41495

---

Common/3dParty/openssl/fetch.sh

Before:
```
real    3m6,793s
user    0m28,249s
sys     0m5,641s
```
After:
```
real    0m13,834s
user    0m2,169s
sys     0m0,838s
```

Speed up cloning openssl

---

Common/3dParty/icu/fetch.bat
Common/3dParty/icu/fetch.sh
Common/3dParty/icu/fetch_mobile.sh

Fix https://github.com/ONLYOFFICE/DocumentServer/issues/656

---

Common/DocxFormat/Source/XlsxFormat/Worksheets/Worksheet.cpp
XlsxSerializerCom/Writer/BinaryReader.cpp

Abs negative comment coordinates and offset as Excel does

[x2t] For bug 44039

---

XlsxSerializerCom/Writer/BinaryReader.cpp

[x2t] For bug 38945

---

Common/DocxFormat/Source/DocxFormat/Logic/ParagraphProperty.h

Move m_oFirstLine, m_oHanging from CTwipsMeasure(unsigned) to CSignedTwipsMeasure

[x2t] Fix bug 44466

---

X2tConverter/build/Android/libx2t/src/main/java/lib/x2t/X2t.kt

Android mobile

---

PdfWriter/Src/Annotation.cpp

Fix the problem with PDF/A conformance

Fix bug #46164

---

DesktopEditor/raster/Metafile/Wmf/WmfTypes.h

Fix the problem with reading WmfRect object

Fix bug #45498

---

ASCOfficePPTXFile/Editor/BinaryFileReaderWriter.cpp

Fix out_of_range while binary reading

[x2t] Fix bug 46352

---

ASCOfficePPTXFile/PPTXFormat/Logic/TextParagraphPr.h
ASCOfficePPTXFile/PPTXFormat/Logic/UniFill.cpp
Common/DocxFormat/Source/DocxFormat/Logic/Pict.h

Fix omitted break statement in switch

[x2t] Fix bug 46384

---

ASCOfficeDocxFile2/BinReader/DocumentRelsWriter.h
ASCOfficeDocxFile2/BinReader/FileWriter.cpp
ASCOfficeDocxFile2/BinReader/FileWriter.h
ASCOfficeDocxFile2/BinReader/Readers.cpp
ASCOfficeDocxFile2/BinWriter/BinReaderWriterDefines.h
ASCOfficeDocxFile2/BinWriter/BinWriters.cpp
ASCOfficeDocxFile2/DocWrapper/DocxSerializer.cpp
ASCOfficePPTXFile/Editor/BinReaderWriterDefines.h
ASCOfficePPTXFile/Editor/Converter.h
ASCOfficePPTXFile/Editor/PPTXWriter.h
ASCOfficePPTXFile/Editor/XmlWriter.h
ASCOfficePPTXFile/PPTXFormat/FileFactory.cpp
ASCOfficePPTXFile/PPTXFormat/Logic/HeadingVariant.cpp
ASCOfficePPTXFile/PPTXFormat/Logic/HeadingVariant.h
ASCOfficePPTXFile/PPTXFormat/Namespaces.h
ASCOfficePPTXFile/PPTXLib/Linux/PPTXFormatLib/PPTXFormatLib.pro
ASCOfficePPTXFile/PPTXLib/Linux/PPTXFormatLib/pptxformatlib_logic.cpp
Common/DocxFormat/Source/DocxFormat/FileFactory.cpp
Common/DocxFormat/Source/DocxFormat/FileTypes.h
XlsxSerializerCom/Common/BinReaderWriterDefines.h
XlsxSerializerCom/Common/Common.h
XlsxSerializerCom/Reader/BinaryWriter.cpp
XlsxSerializerCom/Writer/BinaryReader.cpp

Add reading/writing of docProps/custom.xml

[x2t] For bug 46739

---

DesktopEditor/doctrenderer/js_internal/v8/v8_base.h

(cherry picked from commit 32847c4e3e560765a0777139f220f4e038061753)
(cherry picked from commit 67550a22e4bf5bcee02bd45c89b97ccbfea46984)

Fix crashes on call js method (if exception works)

---

Fb2File/Fb2File.cpp

also added support for keywords

Fix bug 49713

---

Common/3dParty/html/css/src/CCompiledStyle.cpp

(cherry picked from commit a0402e1096dd7a02413f9c48022f41b3ea5a0bd9)

fix bug #49043

---

Common/3dParty/hunspell/make.py
Common/3dParty/hunspell/wasm/js/spell.js
Common/3dParty/hunspell/wasm/src/engine.h
Common/3dParty/hunspell/wasm/src/filemgr_wrapper_new.cxx
Common/3dParty/hunspell/wasm/src/string_buffer_stream.h

Fix crash in wasm module (if delete engine equal with current)
Own wrapper for stringstream (remove deprecated strstream)

Fix bug 50471

---

PdfWriter/PdfRenderer.cpp

Improve rendering of bold text when there is no bold font

Fix bug #50743

---

PdfWriter/PdfRenderer.cpp
PdfWriter/Src/Utils.h

Fix the problem with escaping text strings

Fix bug #50874

---

Common/3dParty/html/fetch.py

isspaсe crashes when reading unicode characters

fix gumbo-parser

---

ASCOfficeXlsFile2/source/XlsFormat/Binary/CFStreamCacheReader.cpp
ASCOfficeXlsFile2/source/XlsFormat/Logic/Biff_records/BOF.cpp
ASCOfficeXlsFile2/source/XlsFormat/Logic/Biff_records/Label.cpp
ASCOfficeXlsFile2/source/XlsXlsxConverter/XlsConverter.cpp
ASCOfficeXlsFile2/source/XlsXlsxConverter/xlsx_conversion_context.cpp
Common/OfficeFileFormatChecker.h
Common/OfficeFileFormatChecker2.cpp

fix bug #52767

---

PdfWriter/PdfRenderer.cpp

Remove additional space for drop-down list button, because it causes layout problems for right-aligned drop-down lists

For bug #53323

---

PdfReader/Src/RendererOutputDev.cpp

Fix bug 55177

---

ASCOfficePPTFile/PPTFormatLib/PPTXWriter/BulletsConverter.cpp

(cherry picked from commit 64e96529411abc82f14244f3435ad5d16ee642fd)

fix bug #57029

---

DesktopEditor/doctrenderer/docbuilder.h

updated api descriptions for new docbuilder classes and methods

Api descriptions

---

DesktopEditor/graphics/Graphics.cpp
DesktopEditor/graphics/Graphics.h
DesktopEditor/graphics/GraphicsRenderer.cpp
DesktopEditor/graphics/GraphicsRenderer.h
DesktopEditor/graphics/pro/Graphics.h
PdfReader/Src/RendererOutputDev.cpp
PdfReader/lib/xpdf/Gfx.cc

Fix bug 36412, 55591

---

DesktopEditor/doctrenderer/docbuilder.h
DesktopEditor/doctrenderer/docbuilder.net/src/docbuilder.net.h

updated api descriptions for builder wrappers

Api descriptions updates

---

ASCOfficeDocxFile2/DocWrapper/XlsxSerializer.cpp
ASCOfficeOdfFile/src/odf/table_xlsx.cpp
Common/DocxFormat/Source/XlsxFormat/Styles/Styles.h
Common/DocxFormat/Source/XlsxFormat/Worksheets/SheetData.cpp
Common/DocxFormat/Source/XlsxFormat/Worksheets/SheetData.h
Common/DocxFormat/Source/XlsxFormat/Worksheets/Worksheet.cpp
Common/DocxFormat/Source/XlsxFormat/XlsxFlat.cpp
Common/DocxFormat/Source/XlsxFormat/XlsxFlat.h
XlsxSerializerCom/Writer/BinaryReader.cpp

refactoring & fix other bugs spreadsheet 2003 xml

fix bug #58982

---

DesktopEditor/fontengine/FontFile.cpp
DesktopEditor/fontengine/FontFile.h
DesktopEditor/fontengine/FontManager.cpp
PdfReader/Src/RendererOutputDev.cpp

Fix bug 59036

---

DesktopEditor/graphics/pro/js/drawingfile.json
DesktopEditor/graphics/pro/js/qt/nativegraphics.pro
DesktopEditor/graphics/pro/js/wasm/js/drawingfile_base.js
DesktopEditor/graphics/pro/js/wasm/src/CMapSerialize.h
DesktopEditor/graphics/pro/js/wasm/src/drawingfile.cpp
DesktopEditor/graphics/pro/js/wasm/src/drawingfile.h
PdfFile/PdfFile.cpp
PdfFile/PdfFile.h
PdfFile/PdfReader.cpp
PdfFile/PdfReader.h
PdfFile/Resources/BaseFonts.cpp
PdfFile/Resources/BaseFonts.h
PdfFile/Resources/CMapMemory/CMapSerialize.cpp
PdfFile/Resources/CMapMemory/CMapSerialize.pro
PdfFile/Resources/CMapMemory/autogen.py
PdfFile/Resources/CMapMemory/cmap_memory.h
PdfFile/SrcReader/Adaptors.cpp
PdfFile/SrcReader/Adaptors.h
PdfFile/lib/xpdf/CMap.cc
PdfFile/lib/xpdf/CMap.h

Fix bugs 56130, 56904, 59379

---

PdfFile/PdfWriter_empty.cpp
PdfFile/SrcReader/GfxClip.h
PdfFile/SrcReader/RendererOutputDev.cpp

Fix bug 60648

---

Test/Applications/x2tTester/README.md
Test/Applications/x2tTester/x2tTester.cpp
Test/Applications/x2tTester/x2tTester.h
X2tConverter/src/run.h

Fix bug 60966

---

PdfFile/PdfReader.cpp

fix pdf Links

---

Test/Applications/x2tTester/README.md
Test/Applications/x2tTester/x2tTester.cpp
Test/Applications/x2tTester/x2tTester.h

Fix bug 61452

---

DesktopEditor/doctrenderer/docbuilder.h
DesktopEditor/doctrenderer/docbuilder.net/src/docbuilder.net.cpp
DesktopEditor/doctrenderer/docbuilder.net/src/docbuilder.net.h
DesktopEditor/doctrenderer/docbuilder.net/test/Program.cs
DesktopEditor/doctrenderer/docbuilder_p.cpp

Also added `static CDocBuilderValue::CreateArray()` function in docbuilder.

.NET constructor from an array for CDocBuilderValue was implemented

---

PdfFile/PdfReader.cpp

Fixed search for cmap need - now also checks AcroForm, annots and widgets.

Fix bug #64845

---

DesktopEditor/doctrenderer/js_internal/jsc/jsc_base.mm
DesktopEditor/doctrenderer/test/json/main.cpp

- Added `Dispose()` to `~CJSContext()` for JavaScriptCore
- Fixed last test for json

JSC: Automatic Dispose for CJSContext on destruction

---

PdfFile/PdfReader.cpp
PdfFile/SrcReader/PdfAnnot.cpp
PdfFile/SrcReader/RendererOutputDev.cpp

Fix empty font and StemV from FontDescriptor

Fix pdf font

---

DesktopEditor/common/File.cpp
DesktopEditor/common/File.h
OfficeUtils/src/OfficeUtils.h
OfficeUtils/src/ZipUtilsCP.cpp
OfficeUtils/tests/.gitignore
OfficeUtils/tests/main.cpp

CFileBinary::GetTime,
CFileBinary::SetTime was updated
Fix bugs with time in Zip/Unzip

Fix bug 62427

---

Common/3dParty/libvlc/vlcplayer.cpp
Common/3dParty/libvlc/vlcplayer.h

Added couple of functions to `CVlcPlayer` class needed for new footer panel functionality.

Add some functionality to libvlc player

---

DesktopEditor/doctrenderer/docbuilder.python/src/docbuilder.py
DesktopEditor/doctrenderer/docbuilder.python/test/docbuilder_test.py

- File type numeric constants
- Automatic conversion to `CDocBuilderValue` type in function parameters
- Constructor of `CDocBuilderValue` from list

Add new features to python docbuilder wrapper

---

DesktopEditor/graphics/pro/metafile.pri
DesktopEditor/raster/Metafile/svg/CSvgParser.cpp
DesktopEditor/raster/Metafile/svg/SvgObjects/CContainer.h
DesktopEditor/raster/Metafile/svg/SvgObjects/CObjectBase.h
DesktopEditor/raster/Metafile/svg/SvgObjects/CSwitch.cpp
DesktopEditor/raster/Metafile/svg/SvgObjects/CSwitch.h

Added switch implementation in svg

Fix bug #68843

---

DesktopEditor/graphics/Graphics.cpp
DesktopEditor/graphics/Graphics.h
DesktopEditor/graphics/GraphicsLayerBlend.h
DesktopEditor/graphics/GraphicsRenderer.cpp
DesktopEditor/graphics/GraphicsRenderer.h
DesktopEditor/graphics/IRenderer.h
PdfFile/PdfEditor.cpp
PdfFile/PdfEditor.h
PdfFile/PdfFile.cpp
PdfFile/SrcReader/PdfAnnot.cpp
PdfFile/SrcReader/RendererOutputDev.cpp
PdfFile/SrcReader/RendererOutputDev.h
PdfFile/lib/xpdf/Gfx.cc

Fix bugs #69016, #56088, #69019
For bugs #55429, #56118, #45813

Fix bugs #69016, #56088, #69019

---

DesktopEditor/graphics/commands/AnnotField.cpp
DesktopEditor/graphics/commands/AnnotField.h
PdfFile/PdfWriter.cpp
PdfFile/PdfWriter.h
PdfFile/SrcWriter/Annotation.cpp
PdfFile/SrcWriter/Annotation.h
PdfFile/test/test.cpp

Write AP for Ink, FreeText, Line, Square, Circle, Polygon, Polyline annots

For bug 65822

---

DesktopEditor/graphics/Graphics.cpp
PdfFile/PdfEditor.cpp

Fix bugs 69862, 69863
